<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-10T00:27:56 EET" name="Suite" finished-at="2023-12-10T00:27:57 EET" duration-ms="1498">
    <groups>
    </groups>
    <test started-at="2023-12-10T00:27:56 EET" name="Test" finished-at="2023-12-10T00:27:57 EET" duration-ms="1498">
      <class name="CrudMethodTesting.DatabaseTesting">
        <test-method is-config="true" signature="beforetest()[pri:0, instance:CrudMethodTesting.DatabaseTesting@73700b80]" started-at="2023-12-10T00:27:56 EET" name="beforetest" finished-at="2023-12-10T00:27:57 EET" duration-ms="765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method signature="AddOneCustomer()[pri:1, instance:CrudMethodTesting.DatabaseTesting@73700b80]" started-at="2023-12-10T00:27:57 EET" name="AddOneCustomer" finished-at="2023-12-10T00:27:57 EET" duration-ms="560" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '77' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '77' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2081)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246)
at CrudMethodTesting.DatabaseTesting.AddOneCustomer(DatabaseTesting.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddOneCustomer -->
        <test-method signature="UpdateCustomerNumber()[pri:2, instance:CrudMethodTesting.DatabaseTesting@73700b80]" started-at="2023-12-10T00:27:57 EET" name="UpdateCustomerNumber" finished-at="2023-12-10T00:27:57 EET" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateCustomerNumber -->
        <test-method signature="SelectOneCustomer()[pri:3, instance:CrudMethodTesting.DatabaseTesting@73700b80]" started-at="2023-12-10T00:27:57 EET" name="SelectOneCustomer" finished-at="2023-12-10T00:27:57 EET" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SelectOneCustomer -->
        <test-method is-config="true" signature="aftertest()[pri:0, instance:CrudMethodTesting.DatabaseTesting@73700b80]" started-at="2023-12-10T00:27:57 EET" name="aftertest" finished-at="2023-12-10T00:27:57 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- CrudMethodTesting.DatabaseTesting -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
